apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - context: auth
      image: ahmedmaher2481998/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: ./src/**.ts
