apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl

spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ahmedmaher2481998/auth
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: 3000
